language: node_js

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - PLATFORM="linux"
    - os: osx
      osx_image: xcode8.3
      env:
        - PLATFORM="mac"
        - secure: GXCxM+6Cp25aol/V0jt7or0zDmPrvg5+snYQoQsQvAM1K1ERy3XP58TfBjDFKLIL4xlAppabBvfDi2eM0Z+pfnUrRBDJ8zvwGGxaUG3nvMJcmzpJZ+DYgOHxC8ArCrKhJLUT1aONKzl0O2VIcb2OX00xaXu+M1sY1JGM9fxGK45Y2kG/Eu4r42Xgbrujshztww7Q2iMNKqY9f9iPgJMuyBh/bxT+24j+o4HllrqB6TNnwau7rk6th62yWR8uvVGhdMW3MtI7wnAyIVR/203VlowVfdF4zQiTZIHrUhyL7qali8/W+xZhS2BZnDjKg65eFD31TjnjUXg424GX0xC0oNfLt8DXkGI9ag1luuKCtohNSniqlUIFFbGFjjVXndcEqamz1QtX+AZs5Mim0mhrHVD4lzLanQi8uIA0RBz4x3NJp0hBRRQZ9j2aoimlbAld4ggyVdAb9Fc+ppReuXCFi5lTO+3TpIm/eYsV/4PqA4FU9ba0tO5UN80ZTC8AaRd4TW0XyzOLjqsU4NCW73onUYa92WEE1sH2NE18yVCMrOVhNPlMHr3CVbT4F/sBl/85pARiIx2i4fkaAhyZH/HP//09d+eeuk6egEutsAxKSRlo89ab+U2CSZCpmcG6MqHQCxyDne24xVmU7SLRY2CRcdZ871RSZCQbwWQ2NkbDf38=
        - secure: SdjEYibkUjeHx4C3EoHgYb/w+NFIDPGNN9H9RLv0iLR3no6XHvPRTZtGSLRw9MtoyZcZHkQK2rd58HZu1WVfk1aeTsaOCPjI6cwrBKaG7CedPGEy8vVuE0zIqKtwKYUToqZ+jBY/7HpO3lJtcg2vzeuSWqCJy+CGL5i9+ctCfZWsSQAuxmBPoF1XEmYwBlj1R8fZVBAWFB6mLL1zuZzwYBWiclI5YFgOVlscKVHq4PawH9dbX4/v3H6mFZgYM0UU6GlR1u20cL83MoTgPJREj6U8xp+6Dds12A8mpJTjwvK4OFHftdnOiCEk8XqV9QviZbrWvsoM7tNlZgE546BwHhcMFZmTbeVCX6TrmGekrz0f+2fagbKwUWHIp4hpwbul3Mp4HZVKDABQo/LJ4WUpj6fBclHEEsu4cbYerTJPk967K43XkwQXgnRhdVXvOq0DIp9KtiwUYGRrFePKKypSpbfkEFDVU8lyJ74/IZPPGefgREcMYqp/Ms4tmfYX+SwQFNYxwAaMnhfpaPMelnedQ+sHZqe34+XGYIL3xRSzFxEcOLQWiH7ZdZgRAslO7i33Ae6POjteZ+vGKwwHT1fnAkUU4SYrcFaCiXKKNmLCnDIN6sviXwTW7n1BNz60dAt6tBd1KbFezURWggRhl2kRkzGr4AXmx0+qNslXLO2YP6I=
      before_install:
        - openssl aes-256-cbc -K $encrypted_ba646dffc48f_key -iv $encrypted_ba646dffc48f_iv -in code-signing/mac.p12.enc -out code-signing/mac.p12 -d
        - security create-keychain -p $KEYCHAIN_PASS build.keychain
        - security default-keychain -s build.keychain
        - security unlock-keychain -p $KEYCHAIN_PASS build.keychain
        - security import ./code-signing/mac.p12 -k build.keychain -P $MAC_P12_PASSWORD -T /usr/bin/codesign
        - 'security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k keychainPass keychainName'

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - git-all
    - build-essential
    - icnsutils
    - graphicsmagick
    - xz-utils

cache:
  directories:
    - node_modules
    - build/node_modules

install:
- npm install > /dev/null

script:
- npm test

before_deploy:
- npm run build-n-package:$PLATFORM

deploy:
  provider: releases
  api_key:
    secure: RE/7b5bOUu1zgsCLEu/aezuOxlrDG44pLzo4v0kFUNilhU10xBZhpbFRAn7zmFmO9CSq2OEXY/ZnplHIvglel1GM5x5N5kb5t19hIj8ul3wf7ka9fueg1he8VtRpzJOHAw2Rib/Yi5u7PLK/ddcAt39ccRxuSRhaKXYJNWos0ZJfPZbMAdvg6YJq+ep36TFcXxGMC8jQQUOgPb1yGTpChtiK298MenR5AH8qWiZdBnHahm9IQYqPIcSU4xpA7AtEyxgjVZUUPyIgI2/oX+fMyfwxG9fMSgiNt/ZM0dManpTN/yVn7v8D5RNd5U9YLhw8qwmxBFTIvv5PX0AJg0dLMKlvPHRDDbqYDL+/3L+xoaHV2pKtPTMr2/k79EF0V7sW93sdzyA2tcyAqFP5/I38X42tVJGeU/zIFMN4x5Ma+EzFGDT3s/0eiHdr4VGDs7Tv7EsQnQ0RDZTVngQCJY51xEKX9E+DT32mEZNpx790KnzkdORSptx1W/512OAkZ7X06uHWEi4U/KY1LyC7jOnyJ43RdEADfo/H9n/KyVkcYhUjLsFRIrgJHNZnU3usnrHBeRb7r644dmmAdo4yb3V0PYjZIBAsCL7eX4ApiyWoawRTz6LmjPPNtRD+IYOGAvJCki9kPXQcyb4j67xwqQDl5mxygIFRmRFxZeiEA/cdnsY=
  skip_cleanup: true
  file_glob: true
  file:
    - dist/**/*.zip
    - dist/**/*.dmg
    - dist/**/*.deb
    - dist/**/*.AppImage
  on:
    tags: true
