language: node_js

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - PLATFORM="linux"
    - os: osx
      osx_image: xcode7.3
      env:
        - PLATFORM="mac"
        - secure: kYQQjMAkkteAM98T8TLSZMgNtqS1/74kkmdMFBZ/ABfFCmIu2CgbIw19uyKlOEM6BYRu5UhUj1565QbXXAA0o16XbDrQ2qOyPGlz44x0Lh3aNQMXxJae2ukUhK0B1MJqmRJ6GmHkLc5EQbGGLK4VtvcFJkWEWDmXj+7N7Aqqd9e8hQhVI318+3YVjDy8nFFT48cel/y8RDb1ph9KoZKht9/ddbhmvaVkLYsx85Av+cDDsGWX0wdYaB8aYTfsWb8dvU4IR6xYnHln82lTtwIVXmi/G4OYxe+Ep044298kitbILD72oizRIiLtyMrwi6nh4RL7mVBdGhCmBhq0YVejJtwE9q4tErAvspb+8PYUiCaMckhMLaaPnLEJ85v87naVrZv1tc5yfKmqVUCrvAC+MI+F0yjw01S+p1fM9vj5hzuJad3wIR0BF8tBkAwHR75uSjsGm8DMZab4TjX9PUekFHSknrYeGH4wt7ay5fi02E4NGI62Q2RjwYD0REgyIgKChktKoyjgaLrDM/ASLTRzK0KiDiOVkLelzpvcqDEo0ObsHbSztK73a7Nk0cafSOH6CYtxDCJp7+JkWDtYz6wb3ZrtwF5TO17e32IidpS+AYM3J2WuR6OUCLJzk73rXa0Fob0ZXLDXT0cg2e+XR1BC9T+rYgeJMxWPnZG3I82kfgM=
      before_install:
        - security create-keychain -p mysecretpassword build.keychain
        - security default-keychain -s build.keychain
        - security unlock-keychain -p mysecretpassword build.keychain
        - security import ./code-signing/mac.p12 -k build.keychain -P $MAC_P12_PASSWORD -T /usr/bin/codesign
        - security find-identity -v
        - openssl aes-256-cbc -K $encrypted_ba646dffc48f_key -iv $encrypted_ba646dffc48f_iv -in code-signing/mac.p12.enc -out code-signing/mac.p12 -d

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - git-all
    - build-essential
    - icnsutils
    - graphicsmagick
    - xz-utils

install:
- npm install > /dev/null

script:
- npm test

before_deploy:
- npm run build-n-package:$PLATFORM

deploy:
  provider: releases
  api_key:
    secure: RE/7b5bOUu1zgsCLEu/aezuOxlrDG44pLzo4v0kFUNilhU10xBZhpbFRAn7zmFmO9CSq2OEXY/ZnplHIvglel1GM5x5N5kb5t19hIj8ul3wf7ka9fueg1he8VtRpzJOHAw2Rib/Yi5u7PLK/ddcAt39ccRxuSRhaKXYJNWos0ZJfPZbMAdvg6YJq+ep36TFcXxGMC8jQQUOgPb1yGTpChtiK298MenR5AH8qWiZdBnHahm9IQYqPIcSU4xpA7AtEyxgjVZUUPyIgI2/oX+fMyfwxG9fMSgiNt/ZM0dManpTN/yVn7v8D5RNd5U9YLhw8qwmxBFTIvv5PX0AJg0dLMKlvPHRDDbqYDL+/3L+xoaHV2pKtPTMr2/k79EF0V7sW93sdzyA2tcyAqFP5/I38X42tVJGeU/zIFMN4x5Ma+EzFGDT3s/0eiHdr4VGDs7Tv7EsQnQ0RDZTVngQCJY51xEKX9E+DT32mEZNpx790KnzkdORSptx1W/512OAkZ7X06uHWEi4U/KY1LyC7jOnyJ43RdEADfo/H9n/KyVkcYhUjLsFRIrgJHNZnU3usnrHBeRb7r644dmmAdo4yb3V0PYjZIBAsCL7eX4ApiyWoawRTz6LmjPPNtRD+IYOGAvJCki9kPXQcyb4j67xwqQDl5mxygIFRmRFxZeiEA/cdnsY=
  skip_cleanup: true
  file_glob: true
  file:
    - dist/**/*.zip
    - dist/**/*.dmg
    - dist/**/*.deb
    - dist/**/*.AppImage
  on:
    tags: true
